### ISSUE TITLE
default recipe fails under Ubuntu 15.04

### ISSUE THREAD

**Issue by rkeiii** [gmiranda23/ntp#105]
Using 1.8.2 of the NTP cookbook on a host running Ubuntu 15.04 I get this during converge

6.6.6.6   * execute[Force sync hardware clock with system clock] action run (skipped due to only_if)
6.6.6.6   * service[ntp] action enable
6.6.6.6     
6.6.6.6     ================================================================================
6.6.6.6     Error executing action `enable` on resource 'service[ntp]'
6.6.6.6     ================================================================================
6.6.6.6     
6.6.6.6     Chef::Exceptions::Exec
6.6.6.6     ----------------------
6.6.6.6     /bin/systemctl enable ntp returned 1, expected 0
6.6.6.6     
6.6.6.6     Resource Declaration:
6.6.6.6     ---------------------
6.6.6.6     # In /var/chef/cache/cookbooks/ntp/recipes/default.rb
6.6.6.6     
6.6.6.6     112: service node['ntp']['service'] do
6.6.6.6     113:   supports :status => true, :restart => true
6.6.6.6     114:   action   [:enable, :start]
6.6.6.6     115: end
6.6.6.6     
6.6.6.6     Compiled Resource:
6.6.6.6     ------------------
6.6.6.6     # Declared in /var/chef/cache/cookbooks/ntp/recipes/default.rb:112:in `from_file'
6.6.6.6     
6.6.6.6     service("ntp") do
6.6.6.6       provider Chef::Provider::Service::Systemd
6.6.6.6       action [:enable, :start]
6.6.6.6       supports {:status=>true, :restart=>true}
6.6.6.6       retries 0
6.6.6.6       retry_delay 2
6.6.6.6       guard_interpreter :default
6.6.6.6       service_name "ntp"
6.6.6.6       pattern "ntp"
6.6.6.6       cookbook_name "ntp"
6.6.6.6       recipe_name "default"
6.6.6.6     end
6.6.6.6     
6.6.6.6 Recipe: chef-client::systemd_service
6.6.6.6   * service[chef-client] action restart
6.6.6.6     - restart service service[chef-client]
6.6.6.6 Recipe: timezone-ii::debian
6.6.6.6   * bash[dpkg-reconfigure tzdata] action run
6.6.6.6     - execute "bash"  "/tmp/chef-script20150429-1235-1rpe2om"
6.6.6.6 Recipe: ntp::default
6.6.6.6   * service[ntp] action restart
6.6.6.6     - restart service service[ntp]
6.6.6.6 Recipe: ntp::apparmor
6.6.6.6   * service[apparmor] action restart
6.6.6.6     - restart service service[apparmor]
6.6.6.6 
6.6.6.6 Running handlers:
6.6.6.6 [2015-04-29T16:49:40-07:00] ERROR: Running exception handlers
6.6.6.6 Running handlers complete
6.6.6.6 [2015-04-29T16:49:40-07:00] ERROR: Exception handlers complete
6.6.6.6 [2015-04-29T16:49:40-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
6.6.6.6 Chef Client failed. 35 resources updated in 137.16857312 seconds
6.6.6.6 [2015-04-29T16:49:40-07:00] ERROR: service[ntp] (ntp::default line 112) had an error: Chef::Exceptions::Exec: /bin/systemctl enable ntp returned 1, expected 0
6.6.6.6 [2015-04-29T16:49:40-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jrosenboom** [comment]
This looks like a bug in Vivid to me, ` /bin/systemctl enable ntp` is the right command to execute, it even does enable ntp properly, it just fails with some weird error while doing so.

https://bugs.launchpad.net/ubuntu/+source/ntp/+bug/1451743

**Comment by eheydrick** [comment]
I ran into this problem and until systemd is fixed to enable SysV services you can use chef-rewind in a wrapper cookbook to use SysV to enable the service:

```
if node['platform'] == 'ubuntu' && node['platform_version'].to_f >= 15.04
  chef_gem 'chef-rewind'
  require 'chef/rewind'

  include_recipe 'ntp'

  rewind 'service[ntp]' do
    provider Chef::Provider::Service::Init::Debian
  end
else
  include_recipe 'ntp'
end
```

**Comment by rkeiii** [comment]
Thanks for the explanation guys. Hopefully Canonical will get their act together soon.
