### ISSUE TITLE
Parent directory /etc/apparmor.d does not exist. - centos 6.5

### ISSUE THREAD

**Issue by epcim** [gmiranda23/ntp#106]
Using ntp (1.8.2)

On centos 6.5 from docker image I got the error, since the /etc/apparmor.d not exist. Pls add the dir creation first.

```
 Recipe: ntp::apparmor
         * service[apparmor] action nothing (skipped due to action :nothing)
       
           * Parent directory /etc/apparmor.d does not exist.
           ================================================================================
           Error executing action `create` on resource 'cookbook_file[/etc/apparmor.d/usr.sbin.ntpd]'
           ================================================================================
           
           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           Parent directory /etc/apparmor.d does not exist.
       
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/ntp/recipes/apparmor.rb
           
        24: cookbook_file '/etc/apparmor.d/usr.sbin.ntpd' do
            25:   source 'usr.sbin.ntpd.apparmor'
            26:   owner 'root'
            27:   group 'root'
        28:   mode '0644'
            29:   notifies :restart, 'service[apparmor]'
            30: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/ntp/recipes/apparmor.rb:24:in `from_file'
           
           cookbook_file("/etc/apparmor.d/usr.sbin.ntpd") do
         provider Chef::Provider::CookbookFile
             action "create"
             retries 0
       
             default_guard_interpreter :default
             path "/etc/apparmor.d/usr.sbin.ntpd"
             backup 5
             atomic_update true
         source "usr.sbin.ntpd.apparmor"
             declared_type :cookbook_file
         cookbook_name "ntp"
             recipe_name "apparmor"
             mode "0644"
             owner "root"
         group "root"
           end
       

```

**Comment by shortdudey123** [comment]
is apparmor not installed? i would think that `/etc/apparmor.d` would be created on package installation.  if thats the case, then this would be an issue with the image

**Comment by epcim** [comment]
My case was the apparmor was set to be disabled - thus dir probably not created.
I think we should modify the following check in the `attrubutes/default.rb` where now is:
```
default['ntp']['apparmor_enabled'] = true if File.exist? '/etc/init.d/apparmor'
```
add / change to
```
default['ntp']['apparmor_enabled'] = true if File.exist? '/etc/apparmor.d'
```
As the only thing the recipe does is to render `ntp` a template to `apparmor.d` directory. 

Note: Systematic fix would be like > read apparmor cookbook is installed on node, apparmor is installed in system packages, whether it's enabled, what is his configuration directory etc. However there are no such attributes - apparmor cookbook anyway since quite old.

**Comment by gmiranda23** [comment]
@epcim Unfortunately, that check would fail during an initial chef-client run where apparmor had never been installed.  I agree with you that a more systematic fix is required.  The fix would be to make the ntp cookbook depend on 'apparmor'.  In the ntp::apparmor recipe, we'd "include_recipe 'apparmor'".

Thoughts from the community?

**Comment by ckonstanski** [comment]
Apparmor does not exist in CentOS 7. Instead of developing deeper hooks into it, perhaps the reverse would be prudent. If apparmor isn't installed, skip the apparmor stuff.

**Comment by tas50** [comment]
I'm not seeing these issues in Test Kitchen with CentOS 5/6/7 on the latest NTP cookbook.  We've made a lot of changes to the apparmor setup.  Can you give it a try with the new cookbook.
