### ISSUE TITLE
restart service service[apparmor] causes ERROR: SSL Validation failure connecting to host: api.opscode.com  on first run

### ISSUE THREAD

**Issue by rberger** [gmiranda23/ntp#107]
Whenever I bring up a node, the first run of the ntp cookbook failed when it tries to do the restart service service[apparmor] with this error:
```
    - restart service service[ntp]
[2015-05-13T19:51:35+00:00] INFO: cookbook_file[/etc/apparmor.d/usr.sbin.ntpd] sending restart action to service[apparmor] (delayed)
Recipe: ntp::apparmor
  * service[apparmor] action restart[2015-05-13T19:51:35+00:00] INFO: Processing service[apparmor] action restart (ntp::apparmor line 20)
[2015-05-13T19:51:36+00:00] INFO: service[apparmor] restarted

    - restart service service[apparmor]
[2015-05-13T19:51:36+00:00] ERROR: SSL Validation failure connecting to host: api.opscode.com - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

As far as I can tell, I don't see the SSL Validation failure any other time, so I'm pretty sure there isn't a fundamental issue with certs.

Any idea why it does this or how I can make it stop failing?

Thanks!

I am using: 
* Hosted Enterprise Chef (whatever they call the SaaS Chef server nowadays)
* Chef version 12.3.0 on the clients
* ntp cookbook 1.8.2
* chef-provisioning / chef-provisioning-fog (not sure if that matters)

**Comment by gmiranda23** [comment]
@rberger can you let me know how you are setting up apparmor so i can recreate that on my end?  the apparmor supermarket cookbook?

**Comment by rberger** [comment]
I'm not doing anything that I know of to set up apparmor.  ntp.::apparmor  is the only thing in my system doing anything with apparmor from what I can tell.

**Comment by rberger** [comment]
I captured the debug output of the failure. Its at https://gist.github.com/rberger/53587485c35df26ad45d

**Comment by alexanderBendo** [comment]
Same problem here, indeed it happens only on the first run

* ntp 1.8.6
* Ubuntu 12.04
* chef-client 11.18.6

**Comment by tas50** [comment]
Can someone give this a try with the latest version of this cookbook.  We've made changes to the apparmor setup that may resolve these problems.

**Comment by tas50** [comment]
I'm no longer seeing this issue on the test systems.  I'm going to close this out, but feel free to open it back up if it's still happening.
