### ISSUE TITLE
Archlinux does not have a ntpdate package

### ISSUE THREAD

**Issue by evaryont** [gmiranda23/ntp#113]
Per the title, there should be an additional platform/platform_family check to not include the ntpdate package on Arch systems.

**Comment by rtrauntvein** [comment]
This would also be handy to support SUSE / SLES - There is no `ntpdate` package in the repository (it is provided by ntp)

**Comment by bcorner13** [comment]
I am seeing the same thing for debian Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.57-3 x86_64 GNU/Linux

**Comment by flaccid** [comment]
+1 for Arch Linux support in general too.

**Comment by tas50** [comment]
All we need is attributes for Arch.  If someone wants to open that PR I'll gladly merge it.  I don't have access to Arch to test that though.

**Comment by tas50** [comment]
What should the packages that we install on archlinux be?  I can add it, but I don't have a test box.

**Comment by tas50** [comment]
NM.  I'm going to flip the default package attribute from %w(ntp ntpdate) to just ntp.  Only debian and RHEL 7+ want ntp + ntpdate.  This will give us support for arch and suse and probably a few other platforms I can't think of.

**Comment by tas50** [comment]
This will be fixed in the 1.10.0 release. Feel free to open it back up if there's more fixes needed for Arch

**Comment by flaccid** [comment]
Thanks @tas50 I have tested and confirm this is working well for Arch Linux at master. Raised https://github.com/gmiranda23/ntp/pull/136 just to update readme.
