### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [gmiranda23/ntp#115]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by flaccid** [comment]
@gmiranda23 @tas50 I am also happy to help. I have not implemented ntp support in the system cookbook and would prefer to simply consume this one on the high level as a dependency. Would like to help ninja the issues and pull requests.

**Comment by tas50** [comment]
@josephholsten and @flaccid we're welcome to any help on this cookbook.  I'm co-maintainer now and I'm prioritizing keeping up on the PRs / issues during work hours.  If you open up a PR I'll be sure to get back to you.
