### ISSUE TITLE
installer_type must be a kind of [String]

### ISSUE THREAD

**Issue by bagdemir** [gmiranda23/ntp#116]
Currently struggling with the NTP cookbook on a Windows machine, on which chef 11.18.6 is currently installed. While running NTP cookbook, I got following error:

1437420344,,ui,message,    null: Chef::Exceptions::ValidationFailed
1437420344,,ui,message,    null: ----------------------------------
1437420344,,ui,message,    null: Option installer_type must be a kind of [String]!  You passed :custom.
1437420344,,ui,message,    null:
...
1437420344,,ui,message,    null: 36:  windows_package node['ntp']['vs_runtime_productname'] do
1437420344,,ui,message,    null: 37:    source         node['ntp']['vs_runtime_url']
1437420344,,ui,message,    null: 38:    options        '/q'
1437420344,,ui,message,    null: 39>>   installer_type :custom
1437420344,,ui,message,    null: 40:    action         :install
1437420344,,ui,message,    null: 41:    only_if        { node['kernel']['release'].to_f < 6 }
1437420344,,ui,message,    null: 42:  end

According to the documentation of windows_package https://docs.chef.io/resource_windows_package.html 
installer_type can be ":msi". I am not sure that the NTP cookbook does use the windows_package from the windows cookbook, but, from the chef core.

**Comment by tas50** [comment]
According to the docs on both the windows cookbook and core chef this should be a symbol.  Are you running the latest windows cookbook?

**Comment by glensc** [comment]
@tas50 why not add version construct to your `metadata.rb` of required windows cookbook version?

**Comment by tas50** [comment]
I'll probably add that to the next version. An open ended dep was a bad idea

**Comment by tas50** [comment]
The metadata has been updated to require 1.38.0 or later, which should get us around the package changes.
