### ISSUE TITLE
ntp_intres.request: permission denied

### ISSUE THREAD

**Issue by cheesesashimi** [gmiranda23/ntp#133]
Hello,

I've been using this cookbook across all of my hosts and I've observed NTPd spamming `/var/log/messages` with the following:

```
messages-20160131:Jan 28 13:04:33 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
messages-20160131:Jan 28 13:05:35 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
messages-20160131:Jan 28 13:06:35 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
messages-20160131:Jan 28 13:07:35 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
messages-20160131:Jan 28 13:08:36 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
messages-20160131:Jan 28 13:09:36 server1 ntpd_intres[18137]: ntp_intres.request: permission denied
```

It looks like https://github.com/gmiranda23/ntp/commit/a0262ee9e0dcf4891a95b2a7f88452c0ac252707 was merged successfully which should fix the issue, based on my own test config. My question is, will this be released soon? :)

Thanks!
Zack

**Comment by tas50** [comment]
I've released version 1.9.2 to Supermarket with this fix.
