### ISSUE TITLE
Outdated package cache can cause exception in installation of ntp package

### ISSUE THREAD

**Issue by wduncanfraser** [gmiranda23/ntp#139]
While working on a cookbook using test kitchen, found that the Ubuntu 14.0.4 build was failing due to the dependent ntp cookbook. The exception is due to the apt cache being out of date, and trying to install ntp_4.2.6.p5+dfsg-3ubuntu2.14.04.6_amd64.deb when if you look at the mirror at http://us.archive.ubuntu.com/ubuntu/pool/main/n/ntp/, that package no longer exists and has been replaced by ntp_4.2.6.p5+dfsg-3ubuntu2.14.04.7_amd64.deb. Workaround is to force an `apt-get update`.

Exception:
Running handlers:
       [2016-02-06T21:04:02+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-06T21:04:02+00:00] ERROR: Exception handlers complete
       Chef Client failed. 8 resources updated in 14 seconds
       [2016-02-06T21:04:02+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-06T21:04:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-06T21:04:02+00:00] ERROR: apt_package[ntp] (ntp::default line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
       ---- Begin output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.6 ----
       STDOUT: Reading package lists...
       Building dependency tree...
       Reading state information...
       The following extra packages will be installed:
         libopts25
       Suggested packages:
         ntp-doc
       The following NEW packages will be installed:
         libopts25 ntp
       0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
       Need to get 474 kB of archives.
       After this operation, 1677 kB of additional disk space will be used.
       Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main libopts25 amd64 1:5.18-2ubuntu2 [55.3 kB]
       Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main ntp amd64 1:4.2.6.p5+dfsg-3ubuntu2.14.04.6
         404  Not Found [IP: 91.189.91.23 80]
       Fetched 55.3 kB in 0s (74.8 kB/s)
       STDERR: E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.6.p5+dfsg-3ubuntu2.14.04.6_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
       
       E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
       ---- End output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.6 ----
       Ran apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.6 returned 100
       [2016-02-06T21:04:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Perhaps the solution would be to do a `apt-get update` or `yum check-update` prior to package install?

**Comment by tas50** [comment]
Package cache is going to be an issue on any platform for any configuration management system.  If you take a look at the test kitchen configs we're including apt, yum for dnf, and freebsd cookbooks to config / warm caches for those package providers. You'll need to ensure that the apt cookbook is loaded early in the nodes run list, but this shouldn't be done in each community cookbook as update apt multiple times per run.  The apt cookbook properly handles periodic updates and does a pretty solid job at it.
