### ISSUE TITLE
unable to restrict interfaces

### ISSUE THREAD

**Issue by vtolstov** [gmiranda23/ntp#64]
Template does not contain options to not listen on some interfaces, for example i need to exclude all tap interfaces and want to write:
interface ignore wildcard

Please add this option.

**Comment by shortdudey123** [comment]
Docs related to this issue => http://doc.ntp.org/4.2.6p5/miscopt.html#interface

**Comment by glensc** [comment]
option is present, just not documented. see #117

**Comment by vtolstov** [comment]
author does not accept pull request, but silently add this ability, so as you see, my pr from 29 aug 2014...

**Comment by glensc** [comment]
@vtolstov apparenly he committed accidentally some work-in-progress

**Comment by glensc** [comment]
and @gmiranda23 workflow is weird, looks like he avoids merge commits, doing commits by himself (with `git am` or `git cherry-pick`), which results broken github navigation (can't go to original PR from commits, etc). at least should use `#<id>` syntax in rewritten commit messages.
