### ISSUE TITLE
Could you add a link to the github repository and to github issues from the supermarket?

### ISSUE THREAD

**Issue by kkeane** [gmiranda23/ntp#92]
Currently, the supermarket does not have a direct link to github or to the issues, making it somewhat difficult to find it.

**Comment by poliva83** [comment]
:+1:

**Comment by poliva83** [comment]
+1

**Comment by rbowlby** [comment]
+1, had to hunt this thing down by your user name

**Comment by gmiranda23** [comment]
Added.
