### ISSUE TITLE
Recipe not idempotent if there are multiple peers

### ISSUE THREAD

**Issue by kkeane** [gmiranda23/ntp#93]
If you specify multiple peers in attributes, the recipe will sometimes re-generate the ntp.conf file even though nothing has changed. I believe this is because the cookbook iterates over the node['ntp']['peers'] with a simple each statement. It should be sorted before using each, to ensure a consistent ordering.

The same issue probably also exists with restrictions.

**Comment by shortdudey123** [comment]
probably true for servers as well

**Comment by gmiranda23** [comment]
Merged #100
