### ISSUE TITLE
Add Preferred Server Support

### ISSUE THREAD

**Issue by EdHurtig** [gmiranda23/ntp#94]
The List of NTP Servers can have a prefer flag which indicates a preferred NTP server, very helpful for maintaining time consistency without sacrificing redundancy.

### Example
```
server 0.ntp iburst prefer
server 1.ntp iburst
server 2.ntp iburst
```

See the later part of https://blog.logentries.com/2014/03/synchronizing-clocks-in-a-cassandra-cluster-pt-2-solutions/

**Comment by gmiranda23** [comment]
Merged #95
